### ISSUE TITLE
Refactor all configuration json to yaml

### ISSUE THREAD

**Issue by linhsolar** [rdsea/QoA4ML#1]
Move all config files for connections and services deployment in json to a single yaml config for various purposes:
e.g., 
config/rohe_obs
qoa4ml/client, ...

(if needed we can consider another yaml for service (agent, etc.) but I dont see the need as many info are similar for client)

then another yaml file for metrics: metrics.json and system_metric.json

so we have only 2 yaml files, each with many sections. when people do the deployment, they can comment the elements they dont need but we dont need to have many files.

Pls. see https://github.com/rdsea/QoA4ML/blob/main/qoa4ml_lib/conf/client_config.yaml
https://github.com/rdsea/QoA4ML/blob/main/qoa4ml_lib/conf/metric_config.yaml

all configuration files set by the user (when using qoa4ml) should be in QoA4ML/config --> remove all sub conf dirs that actually must be created by the user (config as part of the code is in the code package)

**Comment by minhtribk12** [comment]
Updated, the QoaClient can load/dump configuration from/to both Json and Yaml
