### ISSUE TITLE
qoa4ml lib issue with version

### ISSUE THREAD

**Issue by linhsolar** [rdsea/QoA4ML#12]
the source version is 0.1.8
https://github.com/rdsea/QoA4ML/blob/main/qoa4ml_lib/VERSION
whereas in other places with qoa4ml dependencies we have:
 
qoa4ml==0.1.14
qoa4ml 0.1.13 depends on numpy==1.23.5

the pip is 0.1.14 https://pypi.org/project/qoa4ml/

it causes a lot of problems.

**Comment by minhtribk12** [comment]
all dependencies updated
