### ISSUE TITLE
qoa conf

### ISSUE THREAD

**Issue by linhsolar** [rdsea/QoA4ML#13]
it seems too complicated with many env variables here. Why is QOA_REG_LINK not one element in QOA_CONF? Similar why is LIB_LEVEL not in QOA_CONF?

qoa_conf_path = os.environ.get('QOA_CONF_PATH')
if not qoa_conf_path:
    qoa_conf_path = "./qoa_conf.json"

qoa_reg_link = os.environ.get('QOA_REG_LINK')
if not qoa_reg_link:
    qoa_reg_link = "http://localhost:5010/registration"

qoa_conf = qoa_utils.load_config(qoa_conf_path)

qoaClient = QoaClient(config_dict=qoa_conf, registration_url=qoa_reg_link)

lib_level = os.environ.get('LIB_LEVEL')
if not lib_level:
    lib_level = 5

also: 

1) why is port not defined in conf, if conf is for the service?
2) conf is for QoA so via input file or via env QoA Conf must be in sync

parser.add_argument('--conf', help='configuration file', default="./conf.json")
    parser.add_argument('--port', help='default port', default=5002)
    args = parser.parse_args()

    
    # Serving port
    port = int(args.port)

    # Load configuration file
    config_file = args.conf
    configuration = qoa_utils.load_config(config_file)

**Comment by minhtribk12** [comment]
QOA_REG_LINK - updated to the QoA config
LIB_LEVEL - Use to specify lib packages when running service within container -> passed as an environment variable
port - for serving
config file - for loading ensemble ML models
